export const ADD_PLAYERS_TO_ROSTER = 'ADD_PLAYERS_TO_ROSTER';
export const CREATE_TEAM = 'CREATE_TEAM';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const SIGNOUT_SUCCESS = 'SIGNOUT_SUCCESS'
export const SIGNOUT_ERROR = 'SIGNOUT_ERROR'
export const SORT_ROSTER = 'SORT_ROSTER'